name: Robot Framework Tests

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  robot_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1' # specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Selenium
        pip install robotframework
        pip install robotframework-seleniumlibrary
        pip install robotframework-jsonlibrary


    - name: Run Robot Framework tests
      run: |
       python -m robot --variable  platform:"Windows 10" --variable run_on_LT:yes --variable device:chrome --variable shopLocale:US  --variable version:17.0  ./Tests/PROD_Checklist.robot

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: robot-test-results
        path: output.xml



